name: arraid
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  easy_sidemenu: ^0.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  fluttericon: ^2.0.0
  get: ^4.6.6
  iconsax: ^0.0.8
  iconsax_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: Robotoo
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
